{% set name = "pytest-replay" %}
{% set version = "1.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d1d997d41cd35994a0a8684a29bc7f880148f8215a8ba82dd3cbb8ca9191a02f

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools_scm
  run:
    - pytest >=3.0.0
    - python >=3.8

test:
  imports:
    - pytest_replay

about:
  home: https://github.com/ESSS/pytest-replay
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Saves shell scripts that allow re-execute previous pytest runs to reproduce crashes or flaky tests
  description: Saves previous test runs and allow re-execute previous pytest runs to reproduce crashes or flaky tests
  dev_url: https://github.com/ESSS/pytest-replay

extra:
  recipe-maintainers:
    - nicoddemus
    - tadeu
    - prusse-martin
