{% set name = "pytest-replay" %}
{% set version = "1.5.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: e1a6d2e4f442a2793d75d8c24f59f5632c31494cb84cda046e9f97293ad51fdc

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - setuptools_scm
  run:
    - pytest >=3.0.0
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - pytest_replay

about:
  home: https://github.com/ESSS/pytest-replay
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Saves shell scripts that allow re-execute previous pytest runs to reproduce crashes or flaky tests
  description: Saves previous test runs and allow re-execute previous pytest runs to reproduce crashes or flaky tests
  dev_url: https://github.com/ESSS/pytest-replay

extra:
  recipe-maintainers:
    - nicoddemus
    - tadeu
    - prusse-martin
