{% set name = "pytest-replay" %}
{% set version = "1.1.0" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: caa7d67b93963f626ac0d6382ea3b50b8aac2ca88e4dfa25190297c302700f9c

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . -vv"
  noarch: python

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools_scm    
  run:    
    - pytest >=3.0.0
    - python >=3.6

test:
  imports:
    - pytest_replay

about:
  home: https://github.com/ESSS/pytest-replay
  license: MIT
  license_family: MIT
  license_file: 'LICENSE'
  summary: Saves shell scripts that allow re-execute previous pytest runs to reproduce crashes or flaky tests
  description: "Saves shell scripts that allow re-execute previous pytest runs to reproduce crashes or flaky tests"
  dev_url: https://github.com/ESSS/pytest-replay

extra:
  recipe-maintainers:
    - nicoddemus
    - tadeu
    - prusse-martin
    - marcelotrevisani
